/*
* Automatically generated by 'ng g ng-alain:plugin icon'
* @see https://ng-alain.com/cli/plugin#icon
*/

import {
  CloseCircleOutline,
  PlusCircleOutline,
  SaveOutline,
  FileExcelOutline,
  MenuOutline,
  SearchOutline,
  RestOutline,
  EditOutline,
  DeleteOutline,
  SaveFill,
  SaveTwoTone,
  UndoOutline
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  CloseCircleOutline,
  PlusCircleOutline,
  SaveOutline,
  FileExcelOutline,
  MenuOutline,
  SearchOutline,
  RestOutline,
  EditOutline,
  DeleteOutline,
  SaveFill,
  SaveTwoTone,
  UndoOutline
];
